# https://github.com/google-github-actions/deploy-cloud-functions

name: Deploy to Cloud Functions and Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          ssh-key: '${{ secrets.ARCHIVES_DEPLOY_KEY }}'
      - run: npm ci && npm run build && npm run export
      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HIDEO54_172008 }}'
      - uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: hatenaStars
          runtime: nodejs16
          source_dir: functions
          entry_point: 'index.js'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HIDEO54_172008 }}'
          channelId: live
          projectId: hideo54-172008
